
ALTER PROCEDURE DBO.[Delete_Future_Events] AS

----- DELETE FROM EVENT REGISTRATION FIELDS TABLE -----
DELETE EF
FROM DBO.EventRegistrationFields EF WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON EF.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE()

----- DELETE FROM EVENT REGISTRATIONS TABLE -----
DELETE ER
FROM DBO.EventRegistrations ER WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ER.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE()

----- DELETE FROM EVENT REGISTRATION TYPES TABLE -----
DELETE ERT
FROM DBO.EventRegistrationTypes ERT WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ERT.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE()

----- DELETE FROM EVENT TAGS TABLE -----
DELETE ET
FROM DBO.EventTags ET WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ET.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE()

----- DELETE FROM EVENTS TABLE -----
DELETE E
FROM DBO.[Events] E WITH (NOLOCK)
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE()

GO